### ISSUE TITLE
How to build the target `readpng`?

### ISSUE THREAD

**Issue by QRXqrx** [carolemieux/afl-rb#14]
Hi there,

I'm a student doing fuzzing research. I notice that your used the  `readpng`  in the project `libpng` as one of the fuzz targets. I'd like to know how to build it. I have struggled to libpng-1.6.39, 1.6.34 and 1.2.59, but none of these project can make build for `readpng`. The `readpng` I refer to is the `readpng.c` file under `<libpng-src-root>/contrib/gregbook/`.

**Comment by carolemieux** [comment]
Hello! Welcome to doing fuzzing research :)

I'm afraid I built `readpng` a *long* time ago (i.w. 2017), and I don't have precise instructions for building it. Luckily it is no longer 2017 and there are lots of projects out there that have been fuzzed well and have better build instructions. I suggest you use a well-established png target instead, like the png_reader target that lives in google's fuzzer benchmark suite: https://github.com/google/fuzzer-test-suite. You may also want to check out benchmarks suites like: https://hexhive.epfl.ch/magma/.

Good luck! Closing this for now as it is not directly related to afl-rb.

**Comment by QRXqrx** [comment]
These days, I have just worked out a way to build `readpng` in `libpng-1.6.39` mannully. I do consult the work you mentioned (Google FTS and Magma). Anyway, thank u for your kind response :-) .
